/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AuthImport } from './routes/_auth'
import { Route as AppImport } from './routes/_app'
import { Route as IndexImport } from './routes/index'
import { Route as AppUsersIndexImport } from './routes/_app/users/index'
import { Route as AppRelaysIndexImport } from './routes/_app/relays/index'
import { Route as AppEstatesIndexImport } from './routes/_app/estates/index'
import { Route as AppDevicesIndexImport } from './routes/_app/devices/index'
import { Route as AuthAuthLoginImport } from './routes/_auth/auth/login'
import { Route as AppSystemSettingsImagesImport } from './routes/_app/system-settings/images'
import { Route as AppSystemSettingsAccountInformationImport } from './routes/_app/system-settings/account-information'
import { Route as AppEstatesCreateImport } from './routes/_app/estates/create'
import { Route as AppEstatesEstateIdImport } from './routes/_app/estates/$estateId'

// Create/Update Routes

const AuthRoute = AuthImport.update({
  id: '/_auth',
  getParentRoute: () => rootRoute,
} as any)

const AppRoute = AppImport.update({
  id: '/_app',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const AppUsersIndexRoute = AppUsersIndexImport.update({
  path: '/users/',
  getParentRoute: () => AppRoute,
} as any)

const AppRelaysIndexRoute = AppRelaysIndexImport.update({
  path: '/relays/',
  getParentRoute: () => AppRoute,
} as any)

const AppEstatesIndexRoute = AppEstatesIndexImport.update({
  path: '/estates/',
  getParentRoute: () => AppRoute,
} as any)

const AppDevicesIndexRoute = AppDevicesIndexImport.update({
  path: '/devices/',
  getParentRoute: () => AppRoute,
} as any)

const AuthAuthLoginRoute = AuthAuthLoginImport.update({
  path: '/auth/login',
  getParentRoute: () => AuthRoute,
} as any)

const AppSystemSettingsImagesRoute = AppSystemSettingsImagesImport.update({
  path: '/system-settings/images',
  getParentRoute: () => AppRoute,
} as any)

const AppSystemSettingsAccountInformationRoute =
  AppSystemSettingsAccountInformationImport.update({
    path: '/system-settings/account-information',
    getParentRoute: () => AppRoute,
  } as any)

const AppEstatesCreateRoute = AppEstatesCreateImport.update({
  path: '/estates/create',
  getParentRoute: () => AppRoute,
} as any)

const AppEstatesEstateIdRoute = AppEstatesEstateIdImport.update({
  path: '/estates/$estateId',
  getParentRoute: () => AppRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_app': {
      preLoaderRoute: typeof AppImport
      parentRoute: typeof rootRoute
    }
    '/_auth': {
      preLoaderRoute: typeof AuthImport
      parentRoute: typeof rootRoute
    }
    '/_app/estates/$estateId': {
      preLoaderRoute: typeof AppEstatesEstateIdImport
      parentRoute: typeof AppImport
    }
    '/_app/estates/create': {
      preLoaderRoute: typeof AppEstatesCreateImport
      parentRoute: typeof AppImport
    }
    '/_app/system-settings/account-information': {
      preLoaderRoute: typeof AppSystemSettingsAccountInformationImport
      parentRoute: typeof AppImport
    }
    '/_app/system-settings/images': {
      preLoaderRoute: typeof AppSystemSettingsImagesImport
      parentRoute: typeof AppImport
    }
    '/_auth/auth/login': {
      preLoaderRoute: typeof AuthAuthLoginImport
      parentRoute: typeof AuthImport
    }
    '/_app/devices/': {
      preLoaderRoute: typeof AppDevicesIndexImport
      parentRoute: typeof AppImport
    }
    '/_app/estates/': {
      preLoaderRoute: typeof AppEstatesIndexImport
      parentRoute: typeof AppImport
    }
    '/_app/relays/': {
      preLoaderRoute: typeof AppRelaysIndexImport
      parentRoute: typeof AppImport
    }
    '/_app/users/': {
      preLoaderRoute: typeof AppUsersIndexImport
      parentRoute: typeof AppImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexRoute,
  AppRoute.addChildren([
    AppEstatesEstateIdRoute,
    AppEstatesCreateRoute,
    AppSystemSettingsAccountInformationRoute,
    AppSystemSettingsImagesRoute,
    AppDevicesIndexRoute,
    AppEstatesIndexRoute,
    AppRelaysIndexRoute,
    AppUsersIndexRoute,
  ]),
  AuthRoute.addChildren([AuthAuthLoginRoute]),
])

/* prettier-ignore-end */
